Repository eiffel-community/eiffel-intelligence-frontend, pull requests merged in 2019-08, with the labels that each got.

#235 Use LDAP container for IT tests
  .travis.yml
  src/integrationtest/resources/integration-test.properties
  src/main/docker/docker-compose.yml
  src/main/docker/ldap-seed/addAll.sh
  src/main/docker/ldap-seed/gauss.ldif
  src/main/docker/ldap-seed/newton.ldif
Labels: test

#238 Add compatiblity section in README
  README.md
Labels: documentation

#234 Add script to run system tests
  .travis.yml
  src/main/docker/Dockerfile-Jenkins
  src/main/docker/README.md
  src/main/docker/docker-compose.yml
  src/systemtest/java/com/ericsson/ei/systemtest/artifactflow/ArtifactFlowSteps.java
  src/systemtest/java/com/ericsson/ei/systemtest/sourcechangeflow/SourceChangeFlowSteps.java
  src/systemtest/java/com/ericsson/ei/systemtest/testexecutionflow/TestExecutionFlowSteps.java
  src/systemtest/java/com/ericsson/ei/systemtest/utils/StepsUtils.java
  src/systemtest/resources/eiffel-intelligence.sh
  src/systemtest/resources/system-test.properties
Labels: documentation, test

#239 Added configuration documentation.
  src/main/resources/application.properties
  wiki/markdown/configuration.md
  wiki/markdown/docker.md
  wiki/markdown/running-eiffel-intelligence-frontend.md
  wiki/site.xml
Labels: documentation

#240 Change documentation information about repeat
  wiki/markdown/add-subscription.md
Labels: documentation

#243 Integration test updated for multi LDAP
  .travis.yml
  src/integrationtest/resources/features/auth.feature
  src/integrationtest/resources/integration-test.properties
  src/main/docker/docker-compose.yml
  src/main/docker/env.bash
  src/main/docker/ldap-seed/addAll.sh
  src/main/docker/ldap-seed/gauss.ldif
  src/main/docker/ldap-seed/ldap-users-first.ldif
  src/main/docker/ldap-seed/ldap-users-second.ldif
  src/main/docker/ldap-seed/newton.ldif
Labels: code improvements
